import 'package:get/get.dart';

class UIText extends Translations {
  @override
  Map<String, Map<String, String>> get keys {
    return {
      'en_US': {
        'otp': 'OTP',
        'phone_number': 'Phone No',
        'otp_verification': 'OTP Verification',
        'enter_phone_details_1': 'We will send you a One Time Password',
        'enter_phone_details_2': 'on this number.',
        'enter_otp_prompt': 'Enter the OTP sent to ',
        'submit': 'Submit',
        'user_meta_info_greeting': 'Hi, ',
        'user_meta_info_prompt': 'Please Enter Your Details',
        'full_name': 'Full Name',
        'business_account': 'Business Account',
        'user_meta_info_sign': 'By registering, you accept the ',
        'terms_of_use': 'Terms of Use',
        '&': ' & ',
        'privacy_policy': 'Privacy Policy',
        'register': 'Register',
        'lane_dane': 'Lane Dane',
        'new_transaction': 'New Transaction',
        'help': 'Help',
        'feedback': 'Feedback',
        'rate_us': 'Rate Us',
        'share_with_friend': 'Share With Friend',
        'about_us': 'About Us',
        'change_language': 'Change Language',
        'log_out': 'Log Out',
        'update_the_app': 'Update the app',
        'help_page_concern': 'How can we help you?',
        'help_page_prompt':
            'It looks like you are experiencing an issue while using our app. We are here to help, so please get in touch with us!',
        'chat_with_us': 'Chat with us',
        'your_feedback': 'Your Feedback',
        'feedback_quote': 'Give your best time for this moment.',
        'send': 'Send',
        'about_us_text_1':
            'We at Vue Nice Technologies are pleased to have you on board with us.',
        'about_us_text_2':
            'Here, at Vue Nice Technologies we are fully committed to making products that you will come to rely on.',
        'about_us_text_3':
            'We believe that the best ideas come from inspiration and building upon those ideas is the way forward.',
        'about_us_text_4':
            'You can reach out to us through Whatsapp, Instagram, Snapchat.',
        'language_setting_prompt_1': 'Choose Your Language',
        'user_transaction_animated_text_1':
            'Create your first\nLane Dane\n(Transaction Record)\nby clicking the button below',
        'no_pending_amount': 'No Pending Amount',
        'all_transaction_empty_message': 'No sms found in your inbox ☹️',
        'sms_permission_prompt_1':
            'Please give sms read\npermission to see your\ntransaction sms details',
        'sms_permission_safety_1':
            'We will not upload your sms or account data',
        'sms_permission_safety_2': 'or share with anyone',
        'okay': 'Okay',
        'sms_loading_text_1':
            'Please wait while we are\nProcessing your sms to\nshow transactions.',
        'contact_permission_prompt_1':
            'Please give contact\npermission to add\ntransaction with your\ncontact',
        'contact_permission_safety_1':
            'We will not upload your contact or account data',
        'contact_permission_safety_2': 'or share with anyone',
        'contact_loading_text_1':
            'Please wait while we are\nProcessing your contacts to\nshow user list.',
        'name': 'Name',
        'phone': 'Phone',
        'total': 'Total',
        'alltime': 'All time',
        'lastweek': 'Last Week',
        'thisweek': 'This Week',
        'lastmonth': 'Last Month',
        'thismonth': 'This Month',
        'sms': 'SMS',
        'lane': 'Lane',
        'dane': 'Dane',
        'done': 'Done',
        'pending': 'Pending',
        'accept': 'Accept',
        'decline': 'Decline',
        'accepted': 'Accepted',
        'declined': 'Declined',
        'requested': 'Requested',
        'you_requested': 'You Requested',
        'user_profile': 'User Profile',
        'select_contact': 'Select Contact',
        'search_contact': 'Search Contact',
        'add_transaction': 'Add Transaction',
        'transaction_type': 'Transaction Type',
        'payment_status': 'Payment Status',
        'settle_up': 'Settle Up',
        'add_category': 'Add Category',
        'enter_category': 'Enter Category',
        'transaction_detail': 'Transaction Detail',
        'created_at': 'Created At',
        'updated_at': 'Updated At',
        'transaction_for': 'Transaction For',
        'due_date': 'Due Date',
        'confirmation': 'Confirmation',
        'lane_dane_tag_1': 'Keep Your Transaction Record',
        'hindi': 'हिंदी',
        'english': 'English',
        'tamil':'தமிழ்',
        'marathi':'मराठी',
        'new_transaction_message':
            '@name is inviting you to confirm transaction of amount \u{20B9}@amount on the LaneDane app. ',
        'invite_prompt': 'Download the app from link below. \n@link',
        'lane_done_helper_text': 'You have taken \u{20B9}@amount from @name',
        'lane_pending_helper_text': 'You will take \u{20B9}@amount from @name',
        'dane_done_helper_text': 'You have given \u{20B9}@amount to @name',
        'dane_pending_helper_text': 'You will give \u{20B9}@amount to @name',
        'add_contact': 'Add Contact',
        'contact_name': 'Contact Name',
        'contact_phone': 'Contact Phone Number',
        'today': 'Today',
        'yesterday': 'Yesterday',
        'add_group_transaction': 'Add Group Transaction',
        'filter_transaction_participants': 'Select Participants',
        'new_group': 'New Group Split',
        'new_contact': 'New Contact',
        'group_name': 'Group Name',
        'participants': 'Participants',
        'bank_credit': 'Bank Credit',
        'bank_debit': 'Bank Debit',
        'groups': 'Groups',
        'users': 'Users',
        'record_transaction': 'Record Transaction',
      },
      'hi_IN': {
        'otp': 'OTP',
        'phone_number': 'फ़ोन नंबर',
        'otp_verification': 'OTP सत्यापन',
        'enter_phone_details_1': 'हम आपको वन टाइम पासवर्ड भेजेंगे',
        'enter_phone_details_2': 'इस नंबर पर',
        'enter_otp_prompt': 'भेजा गया OTP दर्ज करें',
        'submit': 'सबमिट',
        'user_meta_info_greeting': 'नमस्ते👋🏻, लेन देन में आपका स्वागत है',
        'user_meta_info_prompt': 'कृपया अपना विवरण दर्ज करें',
        'full_name': 'पूरा नाम',
        'business_account': 'व्यावसायिक खाता',
        'user_meta_info_sign': 'पंजीकरण करके, आप स्वीकार करते हैं',
        'terms_of_use': 'उपयोग की शर्तें',
        '&': ' और ',
        'privacy_policy': 'गोपनीयता नीति',
        'register': 'रजिस्टर',
        'lane_dane': 'लेन देन',
        'new_transaction': 'नया लेन-देन',
        'help': 'मदद',
        'feedback': 'प्रतिक्रिया',
        'rate_us': 'हमें रेट करें',
        'share_with_friend': 'मित्र के साथ साझा करें',
        'about_us': 'हमारे बारे में',
        'change_language': 'भाषा बदलें',
        'log_out': 'लॉग आउट',
        'update_the_app': 'ऐप्लीकेशन अपडेट करें',
        'help_page_concern': 'हम आपकी कैसे मदद कर सकते हैं?',
        'help_page_prompt':
            'ऐसा लगता है कि आप हमारे ऐप का उपयोग करते समय किसी समस्या का सामना कर रहे हैं। हम यहां मदद करने के लिए हैं, इसलिए कृपया हमसे संपर्क करें!',
        'chat_with_us': 'हमारे साथ चैट करें',
        'your_feedback': 'आपकी प्रतिक्रिया',
        'feedback_quote': 'इस पल के लिए अपना सर्वश्रेष्ठ समय दें।',
        'send': 'भेजें',
        'about_us_text_1':
            'Vue Nice Technology में आपको अपने साथ शामिल करके हमें खुशी हो रही है।',
        'about_us_text_2':
            'यहां, Vue Nice Technology में हम ऐसे उत्पाद बनाने के लिए पूरी तरह से प्रतिबद्ध हैं जिन पर आप भरोसा करेंगे।',
        'about_us_text_3':
            'हम मानते हैं कि सबसे अच्छे विचार प्रेरणा से आते हैं और उन विचारों पर आगे बढ़ना ही आगे का रास्ता है।',
        'about_us_text_4':
            'आप व्हाट्सएप, इंस्टाग्राम, फेसबुक या ट्विटर के जरिए हम तक पहुंच सकते हैं।',
        'language_setting_prompt_1': 'अपनी भाषा चुनें',
        'user_transaction_animated_text_1':
            'नीचे दिए गए बटन पर\nक्लिक करके अपना पहला\nलेन-देन रिकॉर्ड बनाएं',
        'no_pending_amount': 'कोई बकाया राशि नहीं',
        'all_transaction_empty_message':
            'आपके इनबॉक्स में कोई एसएमएस नहीं मिला ☹️',
        'sms_permission_prompt_1':
            'कृपया अपने लेन-देन\nएसएमएस विवरण देखने के लिए \nएसएमएस पढ़ने की अनुमति दें',
        'sms_permission_safety_1': 'हम आपका एसएमएस या खाता डेटा अपलोड',
        'sms_permission_safety_2': 'या किसी के साथ साझा नहीं करेंगे',
        'okay': 'ठीक',
        'sms_loading_text_1':
            'जब तक हम लेन-देन दिखाने के लिए\nआपके एसएमएस को प्रोसेस कर रहे हैं,\nकृपया प्रतीक्षा करें।',
        'contact_permission_prompt_1':
            'Please give contact\npermission to add\ntransaction with your\ncontact',
        'contact_permission_safety_1':
            'We will not upload your contact or account data',
        'contact_permission_safety_2': 'or share with anyone',
        'contact_loading_text_1':
            'Please wait while we are\nProcessing your contacts to\nshow user list.',
        'name': 'नाम',
        'phone': 'फ़ोन',
        'total': 'कुल',
        'alltime': 'पूरे समय',
        'lastweek': 'पिछले हफ़्ता',
        'thisweek': 'इस हफ़्ता',
        'lastmonth': 'पिछले महीना',
        'thismonth': 'इस महीना',
        'sms': 'एसएमएस',
        'lane': 'लेन',
        'dane': 'देन',
        'done': 'पूर्ण',
        'pending': 'बकाया',
        'accept': 'स्वीकार',
        'decline': 'पतन',
        'accepted': 'स्वीकृत',
        'declined': 'अस्वीकृत',
        'requested': 'अनुरोधित',
        'you_requested': 'आपने अनुरोध किया',
        'user_profile': 'उपयोगकर्ता प्रोफ़ाइल',
        'select_contact': 'संपर्क चुनें',
        'search_contact': 'संपर्क खोजें',
        'add_transaction': 'लेन-देन जोड़ें',
        'transaction_type': 'लेनदेन प्रकार',
        'payment_status': 'भुगतान स्थिति',
        'settle_up': 'सेटल अप',
        'add_category': 'श्रेणी जोड़ें',
        'enter_category': 'श्रेणी दर्ज करें',
        'transaction_detail': 'लेनदेन विवरण',
        'created_at': 'बनाया गया',
        'updated_at': 'अपडेट किया गया',
        'transaction_for': 'लेनदेन के लिए',
        'due_date': 'नियत तारीख',
        'confirmation': 'पुष्टि',
        'lane_dane_tag_1': 'अपना लेन-देन रिकॉर्ड रखें',
        'hindi': 'हिंदी',
        'english': 'English',
        'tamil':'தமிழ்',
        'marathi':'मराठी',
        'new_transaction_message':
            '@name आपको लेन-देन ऐप पर ₹@amount की राशि के लेन-देन की पुष्टि करने के लिए आमंत्रित कर रहे हैं। ',
        'invite_prompt': 'नीचे दिए गए लिंक से ऐप डाउनलोड करें। \n@link',
        'lane_done_helper_text': 'आपने @name से \u{20B9}@amount लिए हैं',
        'lane_pending_helper_text': 'आपको @name से \u{20B9}@amount लेने हैं',
        'dane_done_helper_text': 'आपने @name को \u{20B9}@amount दिए हैं',
        'dane_pending_helper_text': 'आपको @name को \u{20B9}@amount देने हैं',
        'add_contact': 'संपर्क बनाएं',
        'contact_name': 'संपर्क नाम',
        'contact_phone': 'फ़ोन नंबर',
        'today': 'आज',
        'yesterday': 'कल',
        'add_group_transaction': 'Add Group Transaction',
        'filter_transaction_participants': 'Select Participants',
        'new_group': 'New Group Split',
        'new_contact': 'New Contact',
        'group_name': 'Group Name',
        'participants': 'Participants',
        'bank_credit': 'Bank Credit',
        'bank_debit': 'Bank Debit',
        'groups': 'Groups',
        'users': 'Users',
        'record_transaction': 'Record Transaction',
      },
      
      'ta_IN': {
        'otp': 'OTP',
        'phone_number': 'தொலைபேசி எண்',
        'otp_verification': 'OTP சரிபார்ப்பு',
        'enter_phone_details_1': 'நாங்கள் உங்களுக்கு ஒரு முறை கடவுச்சொல்லை அனுப்புவோம்',
        'enter_phone_details_2': 'இந்த எண்ணில்',
        'enter_otp_prompt': 'அனுப்பப்பட்ட OTP ஐ உள்ளிடவும்',
        'submit': 'சமர்ப்பிக்க',
        'user_meta_info_greeting': 'வணக்கம்👋🏻, பரிவர்த்தனைக்கு வரவேற்கிறோம்',
        'user_meta_info_prompt': 'உங்கள் விவரங்களை உள்ளிடவும்',
        'full_name': 'முழு பெயர்',
        'business_account': 'வணிக கணக்கு',
        'user_meta_info_sign': 'பதிவு செய்வதன் மூலம், நீங்கள் ஏற்றுக்கொள்கிறீர்கள்',
        'terms_of_use': 'பயன்பாட்டு விதிமுறைகளை',
        '&': ' மற்றும்',
        'privacy_policy': 'தனியுரிமைக் கொள்கை',
        'register': 'பதிவு',
        'lane_dane': 'பரிமாற்றம்',
        'new_transaction': 'புதிய பரிவர்த்தனை',
        'help': 'உதவி',
        'feedback': 'பின்னூட்டம்',
        'rate_us': 'எங்களை மதிப்பிடு',
        'share_with_friend': 'நண்பருடன் பகிர்ந்து கொள்ளுங்கள்',
        'about_us': 'எங்களை பற்றி',
        'change_language': 'மொழியை மாற்றவும்',
        'log_out': 'வெளியேறு',
        'update_the_app': 'ஏப்ளிகேஷன் அபடேட் கேரன்',

        'help_page_concern': 'நாங்கள் உங்களுக்கு எப்படி உதவ முடியும்?',
        'help_page_prompt':
            'எங்கள் பயன்பாட்டைப் பயன்படுத்தும்போது நீங்கள் சிக்கலைச் சந்திப்பது போல் தெரிகிறது. நாங்கள் உதவ இங்கே இருக்கிறோம், எனவே எங்களை தொடர்பு கொள்ளவும்!',
        'chat_with_us': 'எங்களுடன் அரட்டையடிக்கவும்',
        'your_feedback': 'உங்கள் கருத்து',
        'feedback_quote': 'இந்த தருணத்திற்கு உங்கள் சிறந்த நேரத்தை கொடுங்கள்.',
        'send': 'அனுப்பு',
        'about_us_text_1':
            'Vue Nice Technology இல் நீங்கள் எங்களுடன் இணைந்ததில் நாங்கள் மகிழ்ச்சியடைகிறோம்.',
        'about_us_text_2':
            'இங்கே, Vue Nice Technology இல் நீங்கள் நம்பும் தயாரிப்புகளை உருவாக்க நாங்கள் முழுமையாக கடமைப்பட்டுள்ளோம்.',
        'about_us_text_3':
            'சிறந்த யோசனைகள் உத்வேகத்திலிருந்து வருகின்றன மற்றும் அந்த யோசனைகளை உருவாக்குவது முன்னோக்கி செல்லும் வழி என்று நாங்கள் நம்புகிறோம்.',
        'about_us_text_4':
            'நீங்கள் எங்களை WhatsApp, Instagram, Facebook அல்லது Twitter வழியாக அணுகலாம்',
        'language_setting_prompt_1': 'உங்கள் மொழியை தேர்வு செய்யவும்',
        'user_transaction_animated_text_1':
            'கீழே உள்ள பொத்தானில்\nஉங்கள் முதல் கிளிக் செய்வதன் மூலம்',
        'no_pending_amount': 'நிலுவை இல்லை',
        'all_transaction_empty_message':
            'உங்கள் இன்பாக்ஸில் SMS எதுவும் வரவில்லை ☹️',
        'sms_permission_prompt_1':
            'உங்கள் பரிவர்த்தனையை முடிக்கவும்\nSMS விவரங்களைப் பார்க்க\nஎஸ்எம்எஸ் படிக்க அனுமதிக்கவும்',
        'sms_permission_safety_1': 'உங்கள் SMS அல்லது கணக்குத் தரவை நாங்கள் பதிவேற்றுகிறோம்',
        'sms_permission_safety_2': 'அல்லது யாருடனும் பகிர்ந்து கொள்ள மாட்டார்கள்',
        'okay': 'சரி',
        'sms_loading_text_1':
            'பரிவர்த்தனையைக் காண்பிக்கும் வரை\nபரிவர்த்தனையைக் காண்பிக்கும் வரை.',
        'contact_permission_prompt_1':
            'Please give contact\npermission to add\ntransaction with your\ncontact',
        'contact_permission_safety_1':
            'We will not upload your contact or account data',
        'contact_permission_safety_2': 'or share with anyone',
        'contact_loading_text_1':
            'Please wait while we are\nProcessing your contacts to\nshow user list.',
        'name': 'பெயர்',
        'phone': 'தொலைபேசி',
        'total': 'மொத்தம்',
        'alltime': 'எல்லா நேரமும்',
        'lastweek': 'கடந்த வாரம்',
        'thisweek': 'இந்த வாரம்',
        'lastmonth': 'கடந்த மாதம்',
        'thismonth': 'இந்த மாதம்',
        'sms': 'எஸ்எம்எஸ்',
        'lane': 'பாதை',
        'dane': 'கொடுக்க',
        'done': 'முழு',
        'pending': 'பாக்கிகள்',
        'accept': 'ஏற்றுக்கொள்',
        'decline': 'வீழ்ச்சி',
        'accepted': 'ஏற்றுக்கொள்ளப்பட்டது',
        'declined': 'நிராகரிக்கப்பட்டது',
        'requested': 'கோரப்பட்டது',
        'you_requested': 'நீங்கள் கேட்டீர்கள்',
        'user_profile': 'பயனர் சுயவிவரம்',
        'select_contact': 'தொடர்பைத் தேர்ந்தெடுக்கவும்',
        'search_contact': 'தொடர்பு கண்டுபிடிக்க',
        'add_transaction': 'பரிவர்த்தனையைச் சேர்க்கவும்',
        'transaction_type': 'பரிவர்த்தனை வகை',
        'payment_status': 'பணம் செலுத்தும் நிலை',
        'settle_up': 'குடியேறவும்',
        'add_category': 'வகையைச் சேர்க்கவும்',
        'enter_category': 'வகையை உள்ளிடவும்',
        'transaction_detail': 'பரிமாற்ற விவரங்கள்',
        'created_at': 'உருவாக்கப்பட்டது',
        'updated_at': 'புதுப்பிக்கப்பட்டது',
        'transaction_for': 'பரிவர்த்தனைக்கு',
        'due_date': 'நிலையான தேதி',
        'confirmation': 'உறுதிப்படுத்தல்',
        'lane_dane_tag_1': 'உங்கள் பரிவர்த்தனைகளின் பதிவுகளை வைத்திருங்கள்',
        'hindi': 'हिंदी',
        'english': 'English',
        'tamil':'தமிழ்',
        'marathi':'मराठी',
        'new_transaction_message':
            '@name நீங்கள் பரிவர்த்தனை பயன்பாட்டில் ₹@amount பரிவர்த்தனை தொகையை உறுதிப்படுத்த நீங்கள் அழைக்கப்படுகிறீர்கள். ',
        'invite_prompt': 'கீழே கொடுக்கப்பட்டுள்ள இணைப்பிலிருந்து பயன்பாட்டைப் பதிவிறக்கவும். \n@link',
        'lane_done_helper_text': 'நீங்கள் @name இருந்து \u{20B9}@amount எடுத்துள்ளனர்',
        'lane_pending_helper_text': 'உனக்கு @name இருந்து \u{20B9}@amount எடுக்க வேண்டும்',
        'dane_done_helper_text': 'நீங்கள் @name செய்ய \u{20B9}@amount கொடுத்திருக்கிறார்கள்',
        'dane_pending_helper_text': 'உனக்கு @name செய்ய \u{20B9}@amount கொடுக்க வேண்டும்',
        'add_contact': 'தொடர்பை உருவாக்க',
        'contact_name': 'தொடர்பு பெயர்',
        'contact_phone': 'தொலைபேசி எண்',
        'today': 'இன்று',
        'yesterday': 'நாளை',
        'add_group_transaction': 'Add Group Transaction',
        'filter_transaction_participants': 'Select Participants',
        'new_group': 'New Group Split',
        'new_contact': 'New Contact',
        'group_name': 'Group Name',
        'participants': 'Participants',
        'bank_credit': 'Bank Credit',
        'bank_debit': 'Bank Debit',
        'groups': 'Groups',
        'users': 'Users',
        'record_transaction': 'Record Transaction',
      },
      
      'mr_IN': {
        'otp': 'OTP',
        'phone_number': 'फोन नंबर',
        'otp_verification': 'OTP पडताळणी',
        'enter_phone_details_1': 'आम्ही तुम्हाला वन टाइम पासवर्ड पाठवू',
        'enter_phone_details_2': 'या क्रमांकावर',
        'enter_otp_prompt': 'पाठवलेला ओटीपी प्रविष्ट करा',
        'submit': 'प्रस्तुत करणे',
        'user_meta_info_greeting': 'नमस्कार👋🏻, व्यवहारात स्वागत आहे',
        'user_meta_info_prompt': 'कृपया आपले तपशील प्रविष्ट करा',
        'full_name': 'पूर्ण नाव',
        'business_account': 'व्यवसाय खाते',
        'user_meta_info_sign': 'नोंदणी करून, तुम्ही स्वीकार करता',
        'terms_of_use': 'वापरण्याच्या अटी',
        '&': ' आणि ',
        'privacy_policy': 'गोपनीयता धोरण',
        'register': 'नोंदणी करा',
        'lane_dane': 'देवाणघेवाण',
        'new_transaction': 'नवीन व्यवहार',
        'help': 'मदत करा',
        'feedback': 'अभिप्राय',
        'rate_us': 'आम्हाला रेट करा',
        'share_with_friend': 'मित्रासोबत शेअर करा',
        'about_us': 'आमच्याबद्दल',
        'change_language': 'भाषा बदला',
        'log_out': 'बाहेर पडणे',
        'update_the_app': 'अनुप्रयोग अद्यतनित करां',
        'help_page_concern': 'आम्ही तुम्हाला कशी मदत करू शकतो?',
        'help_page_prompt':
            'आमचे अॅप वापरत असताना तुम्हाला समस्या येत असल्याचे दिसते. आम्ही मदत करण्यासाठी येथे आहोत, म्हणून कृपया आमच्याशी संपर्क साधा!',
        'chat_with_us': 'आमच्याशी गप्पा मारा',
        'your_feedback': 'आपला अभिप्राय',
        'feedback_quote': 'या क्षणाला तुमचा सर्वोत्तम वेळ द्या.',
        'send': 'पाठवा',
        'about_us_text_1':
            'Vue Nice Technology मध्ये तुम्ही आमच्यासोबत सामील झाल्यामुळे आम्हाला आनंद होत आहे.',
        'about_us_text_2':
            'येथे, येथे तुमचा विश्वास असेल अशी उत्पादने तयार करण्यासाठी आम्ही पूर्णपणे वचनबद्ध आहोत.',
        'about_us_text_3':
            'आमचा विश्वास आहे की सर्वोत्तम कल्पना प्रेरणेतून येतात आणि त्या कल्पनांवर उभारणी हाच पुढचा मार्ग आहे.',
        'about_us_text_4':
            'तुम्ही आमच्यापर्यंत WhatsApp, Instagram, Facebook किंवा Twitter द्वारे पोहोचू शकता.',
        'language_setting_prompt_1': 'तुमची भाषा निवडा',
        'user_transaction_animated_text_1':
            'नीचे दिए गए बटन पर\nक्लिक करके अपना पहला\nलेन-देन रिकॉर्ड बनाएं',
        'no_pending_amount': 'कोई बकाया राशि नहीं',
        'all_transaction_empty_message':
            'आपके इनबॉक्स में कोई एसएमएस नहीं मिला ☹️',
        'sms_permission_prompt_1':
            'कृपया तुमचा व्यवहार पूर्ण करा\nएसएमएस तपशील पाहण्यासाठी \nएसएमएस वाचण्याची परवानगी द्या',
        'sms_permission_safety_1': 'आम्ही तुमचा SMS किंवा खाते डेटा अपलोड करतो',
        'sms_permission_safety_2': 'किंवा कोणाशीही शेअर करणार नाही',
        'okay': 'योग्य',
        'sms_loading_text_1':
            'जोपर्यंत आम्ही व्यवहार दाखवत नाही\nतुमच्या एसएमएसवर प्रक्रिया करत आहे,\nकृपया थांबा.',
        'contact_permission_prompt_1':
            'Please give contact\npermission to add\ntransaction with your\ncontact',
        'contact_permission_safety_1':
            'We will not upload your contact or account data',
        'contact_permission_safety_2': 'or share with anyone',
        'contact_loading_text_1':
            'Please wait while we are\nProcessing your contacts to\nshow user list.',
        'name': 'नाव',
        'phone': 'फोन',
        'total': 'एकूण',
        'alltime': 'नेहमी',
        'lastweek': 'गेल्या आठवड्यात',
        'thisweek': 'या आठवड्यात',
        'lastmonth': 'गेल्या महिन्यात',
        'thismonth': 'या महिन्यात',
        'sms': 'एसएमएस',
        'lane': 'लेन',
        'dane': 'द्या',
        'done': 'पूर्ण',
        'pending': 'थकबाकी',
        'accept': 'स्वीकारा',
        'decline': 'पडझड',
        'accepted': 'स्वीकारले',
        'declined': 'नाकारले',
        'requested': 'विनंती केली',
        'you_requested': 'तू विनंती केलीस',
        'user_profile': 'वापरकर्ता प्रोफाइल',
        'select_contact': 'संपर्क निवडा',
        'search_contact': 'संपर्क शोधा',
        'add_transaction': 'व्यवहार जोडा',
        'transaction_type': 'व्यवहाराचा प्रकार',
        'payment_status': 'पैसे भरल्याची स्थिती',
        'settle_up': 'स्थिरस्थावर व्हा',
        'add_category': 'श्रेणी जोडा',
        'enter_category': 'श्रेणी प्रविष्ट करा',
        'transaction_detail': 'व्यवहाराचा तपशील',
        'created_at': 'तयार केले',
        'updated_at': 'अपडेट केले',
        'transaction_for': 'व्यवहारासाठी',
        'due_date': 'निश्चित तारीख',
        'confirmation': 'पुष्टीकरण',
        'lane_dane_tag_1': 'तुमच्या व्यवहारांच्या नोंदी ठेवा',
        'hindi': 'हिंदी',
        'english': 'English',
        'tamil':'தமிழ்',
        'marathi':'मराठी',
        
       'new_transaction_message':
            '@name तुम्हाला ट्रान्झॅक्शन अॅपवर ₹@amount रकमेच्या व्यवहाराची पुष्टी करण्यासाठी आमंत्रित केले आहे. ',
        'invite_prompt': 'खाली दिलेल्या लिंकवरून अॅप डाउनलोड करा। \n@link',
        'lane_done_helper_text': 'आपण @name पासून \u{20B9}@amount घेतले आहे',
        'lane_pending_helper_text': 'आपको @name पासून \u{20B9}@amount घेणे आहे हैं',
        'dane_done_helper_text': 'आपण @name ला \u{20B9}@amount दिले आहे',
        'dane_pending_helper_text': 'तुला @name ला \u{20B9}@amount देणे आवश्यक आहे',
        'add_contact': 'संपर्क तयार करा',
        'contact_name': 'संपर्क नाव',
        'contact_phone': 'फोन नंबर',
        'today': 'आज',
        'yesterday': 'उद्या',
        'add_group_transaction': 'Add Group Transaction',
        'filter_transaction_participants': 'Select Participants',
        'new_group': 'New Group Split',
        'new_contact': 'New Contact',
        'group_name': 'Group Name',
        'participants': 'Participants',
        'bank_credit': 'Bank Credit',
        'bank_debit': 'Bank Debit',
        'groups': 'Groups',
        'users': 'Users',
        'record_transaction': 'Record Transaction',
      },
    };
  }
}
